### ISSUE TITLE
Configurar um container do docker para rodar o projeto

### ISSUE THREAD

**Issue by lcroffi** [fatec-ads-sjc-projects/backend#40]
Para que qualquer um possa rodar o código no seu computador via Docker.
Pode ser feito em um container com uma imagem de Alpine, mas precisa conectar em uma imagem de Postgres com docker-compose.
O build do código (.jar) pode ser feito externamente com um mvn clean package ou um  mvn package docker:build, mas seria legal se fizesse o build dentro do container.

**Comment by PauloKeller** [comment]
Resolvi os problemas de compatibilidade do postgres e da jdk. O build do projeto esta separado para deixar um pouco menor a aplicação.
