### ISSUE TITLE
Provider

### ISSUE THREAD

**Issue by lcroffi** [fatec-ads-sjc-projects/backend#45]
## Classe Provider (Fornecedor)
Criar model, repository, service e controller
Atenção, alguns atributos e tabelas possuem valores fixos.

Requisitos: https://drive.google.com/open?id=1q2OOtivaq4CBlBRGXEun8f9MkinwxQj0
Modelo do banco: https://drive.google.com/open?id=15RxZc_oAmWmCNELlVPDyeKwnABUfU5Ta

Novos requisitos elaborados: https://drive.google.com/open?id=1L4OMren-qGcpD90M7Hefsux6CmLG22HV

**Comment by analimazn** [comment]
**TO DO**
-> Criar funções de atualização de quantidade a cada rodada (limite de compra da Company e amount do Provider)
-> Criar funções de atualização de preços do fornecedor a cada rodada
-> Criar função para salvar os produtos a serem inseridos na proxima rodada. Ex: inserir o lote comprado em uma coluna lotesAInserir no storagCapacityService
-> Criar verificação de região para comprar o pack (Hoje é verificado apenas o tipo de produto)

**Comment by analimazn** [comment]
**TO DO**
-> Criar funções de atualização de quantidade a cada rodada (limite de compra da Company e amount do Provider)
-> Criar funções de atualização de preços do fornecedor a cada rodada
-> Criar função para salvar os produtos a serem inseridos na proxima rodada. Ex: inserir o lote comprado em uma coluna lotesAInserir no storagCapacityService
-> Criar verificação de região para comprar o pack (Hoje é verificado apenas o tipo de produto)
